services:
  # Backend Web Service
  - type: web
    name: chemical-equipment-visualizer-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: static
          name: chemical-equipment-visualizer-frontend
          property: url
      - key: FRONTEND_URL
        fromService:
          type: static
          name: chemical-equipment-visualizer-frontend
          property: url

staticSites:
  # Frontend Static Site
  - name: chemical-equipment-visualizer-frontend
    rootDir: frontend-web
    buildCommand: npm install && npm run build
    publishDir: build
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: chemical-equipment-visualizer-backend
          property: url
